### ISSUE TITLE
ボードの読み込みでエラー

### ISSUE THREAD

**Issue by maxfie1d** [team-e-org/mobile#139]
https://github.com/team-e-org/mobile/blob/dcbe56860d10ced53e9b162ce0c1997c6594304c/lib/view/account_screen.dart#L85

userIDを決め打ちで`111`で取得するようになっているため、ボード一覧の取得に失敗する。
ログイン/登録時に tokenとuserIDが返ってくる仕様に変更されているため、これに準じて修正する

**Comment by dh9489** [comment]
Mock時に許容されたパラメータの使用が原因
userIdの取得への対応で解決可能 #136
