### ISSUE TITLE
sign-in時に帰ってくるuserIdへの対応

### ISSUE THREAD

**Issue by dh9489** [team-e-org/mobile#142]
> * 見積もりのために、`0.25h` `0.5h` `1.0h` `2h` のいずれかのラベルをつけてね☺️
> * Milestoneの設定してね☺️
> * 決まっている場合はAssigneeの設定もしてね☺️
> ![kaguya](https://imgur.com/mVZjByo.png)

**Comment by maxfie1d** [comment]
こちら #136 関連です。
userIdをSharedPreferenceを使って保存すると同時に、boardsRepositoryなどから参照できるようにできたらok
