### ISSUE TITLE
Repositoryをシングルトンにする必要性の議論

### ISSUE THREAD

**Issue by maxfie1d** [team-e-org/mobile#173]
TODO

* Repositoryがシングルトンである必要があるかどうかを議論する
  * RepositoryProviderでインスタンスを流すので、シングルトンにしなくても単一のインスタンスが使用されることが保証されるのでは?
  * シングルトンにする理由がないならば、シングルトンにしないほうがコードがシンプルになるし、想定しないエラーを生まないと思った

**Comment by dh9489** [comment]
経緯としては、元々Singletonで実装していたところに、Providerが加わった流れ

両立させることで考えられるメリットは、Providerを通さずにRepoのインスタンスを通した場合（＝ヒューマンエラー的な）にRepoの一意性を保てることくらい？

今回のケースでは、作業者が限られているので、
基本的にRepoはProviderから取得していることからSingletonを消しても良いのでは？

**Comment by dh9489** [comment]
判決：消す
