### ISSUE TITLE
ピンの作成でCamera/Libraryの選択画面から一つ前の画面に戻れない

### ISSUE THREAD

**Issue by maxfie1d** [team-e-org/mobile#205]
【現状】

✖️ ボタンがないため一つ前の画面に戻れない。

【期待する動作】

✖️ ボタンを配置して一つ前の画面に戻れるようにする。

![image](https://user-images.githubusercontent.com/7913793/85649717-cd34b580-b6de-11ea-8134-187c5abd1c57.png)

**Comment by dh9489** [comment]
fixed in #224
