### ISSUE TITLE
home_screen_blocとboard_detail_screen_blocの処理がほぼ重複している

### ISSUE THREAD

**Issue by maxfie1d** [team-e-org/mobile#242]
TODO

* 共通部分をabstract classにして継承させるなどして共通化させる

**Comment by dh9489** [comment]
ページごとのBlocじゃなくて、ユースケース？ごと（取得したい情報ごとの）のBlocに切り分けてもいいように思っている

**Comment by maxfie1d** [comment]
どう書くのがいいか書きながら考えてみる
