### ISSUE TITLE
pins grid viewのtile高さをchildの高さにする

### ISSUE THREAD

**Issue by dh9489** [team-e-org/mobile#50]
StaggeredGridViewを導入したものの、Tileそれぞれに対して、縦横比を設定しないといけないようす
tileとする子コンポーネントを先に描画して比率を計算し、再度描画する？など対策を考える必要あり。

ーこれまでにやったことー
想定より時間がかかりそうなので、StaggeredGridViewは使用したまま縦横比を固定として残している

**Comment by maxfie1d** [comment]
#105 で解決済み
