### ISSUE TITLE
ピンの作成過程でカメラロールから写真を選択できる

### ISSUE THREAD

**Issue by maxfie1d** [team-e-org/mobile#73]
TODO

* カメラロールにアクセスする方法を調べる
* AndroidとiOSで動作確認をする
* 画像を読み込んで、バイト列に変換できることを確認する

![image](https://user-images.githubusercontent.com/7913793/84619124-306c5e00-af0f-11ea-9a1f-16f0deafa451.png)

---

Related #6

**Comment by maxfie1d** [comment]
これちょっとだけ調べてみたんだけど、flutter公式のimage_pickerというパッケージがあるらしい
https://pub.dev/packages/image_picker

思ったよりけっこう簡単に実装できそう
http://karmactonics.hatenablog.com/entry/2018/09/01/011255

**Comment by dh9489** [comment]
#120 で解決
